export class BroadcasterVideos {
    broadcaster_channel_id: number;
    language_id: number;
    video_name: string;
    rank: number;
    video_thumbnail: string;
    video_description: string;
    url: string;
    duration: number = 0;
    is_active: boolean;
    is_live: boolean;
    is_youtube: boolean;
    is_primary:boolean=false;
    live_ads: boolean = false;
    p160: boolean = false;
    p360: boolean = false;
    p720: boolean = false;
    p1080: boolean = false;
    p_uhd: boolean = false;
    video_type: string;
    yt_streamkey: string;
    fb_streamkey: string;
    ha_streamkey: string;
    created_by: string;
    updated_by: string;
    ps_streamkey:string;
    fp_start_time:string;
    yt_start_time:string;
    ps_start_time:string;
    ha_start_time:string;
    fb1_start_time:string;
    fb2_start_time:string;
    fb3_start_time:string;
    fb4_start_time:string;
    fb5_start_time:string;
    w_application_name:string;
    w_get_target_api:string;
    fb1_streamkey: string;
    fb2_streamkey: string;
    fb3_streamkey: string;
    fb4_streamkey: string;
    fb5_streamkey: string;
    
}