export class BroadcasterVideos
{
    id:number;
    broadcaster_channel_id:number;
    video_name:string;
    rank:number;
    video_thumbnail:string;
    video_description:string;
    video_url:string; 
    is_active:boolean; 
    is_live:boolean;
    is_youtube:boolean;
    yt_streamkey:string;
    fb_streamkey:string;
    ha_streamkey:string;
    created_by:string; 
    updated_by:string;
    updated_on:string;
}