export class JournalSetting{
    id: number;
    journal_id: number;
    language_id: number;
    appln_name: string;
    host_url: string;
    host_port: string;
    stream_name: string;
    suname: string;
    spwd: string;
    req_mac_addr: string;
    output_url_hls: string;
    output_url_rtsp: string;
    is_record: string;
    is_upload: string;
    is_active: string;
    created_by: string;
    updated_by: string;
    ftp_host: string;
    ftp_port: number;
    ftp_uname: string;
    ftp_passwd: string;
    ftp_path: string;
    ha_ftp_host: string;
    ha_ftp_port: number;
    ha_ftp_uname: string;
    ha_ftp_passwd: string;
    ha_ftp_path: string;
}
