export class LoginResponse{
    user_id:number;
    user_app_id:number;
    user_type:string;
    user_name:string;
    user_short_name:string;
    user_emialid:string;
    user_mobile:string;
    user_country_code:string;
    user_country:string;
    user_city:string;
    user_session_id:number;
    user_auth_token:string;
    auth_token_expire:Date;
    client_id:number;
    shop_name:string;
    shop_code:number;
    w_appname:string;
    primary_channel_id:number;
    w_get_target_url:string
}